
RELAY_1_PIN = 0
RELAY_2_PIN = 0
RELAY_3_PIN = 0
RELAY_4_PIN = 0
RELAY_5_PIN = 0
RELAY_6_PIN = 15
RELAY_7_PIN = 20
RELAY_8_PIN = 21
HIGH_POWER_RELAY_PIN = 12


# Peristaltic pumps.
MEDIA_IN_PIN = RELAY_8_PIN
MEDIA_OUT_PIN = RELAY_7_PIN
SUPPLEMENTAL_MEDIA_IN_PIN = RELAY_6_PIN

# Hotplate.
HOTPLATE_PIN = HIGH_POWER_RELAY_PIN

# Leds
RED_LED_PIN = 6
GREEN_LED_PIN = 26
BLUE_LED_PIN = 13
YELLOW_LED_PIN = 19
