
RELAY_1_PIN = 12
RELAY_2_PIN = 16
RELAY_3_PIN = 25
RELAY_4_PIN = 0
RELAY_5_PIN = 0
RELAY_6_PIN = 0
RELAY_7_PIN = 0
RELAY_8_PIN = 0
HIGH_POWER_RELAY_PIN = 24




# Peristaltic pumps.
MEDIA_IN_PIN = RELAY_1_PIN
MEDIA_OUT_PIN = RELAY_2_PIN
SUPPLEMENTAL_MEDIA_IN_PIN = RELAY_3_PIN

# Hotplate.
HOTPLATE_PIN = HIGH_POWER_RELAY_PIN

# Leds
RED_LED_PIN = 26
GREEN_LED_PIN = 19
BLUE_LED_PIN = 21
YELLOW_LED_PIN = 20
